repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
    files: ".*\\.(?:tex|py)$"
- repo: https://github.com/jonasbb/pre-commit-latex-hooks
  rev: v1.3.0
  hooks:
  - id: cleveref-capitalization
  - id: no-space-in-cite
  - id: tilde-cite
  - id: unique-labels
